### ISSUE TITLE
关于视觉惯性历程计的问题

### ISSUE THREAD

**Issue by edgar-explorer** [meyiao/ImuFusion#1]
大哥，您好！
之前看过您的视频，最近在研究有些问题想请教您一下。因为没有其余的联系方式，冒昧在github留言。
如果在紧耦合的VIO中，使用fast或者harris,利用光流进行跟踪。联立相机误差和IMU误差进行优化。请问此时相机的误差是像ORB-SLAM一样的几何误差还是像DSO一样的光度误差？
                                                                          万分感谢

**Comment by meyiao** [comment]
你好! 这里应该用几何误差。港科大的VINS_Mobile就是按你说的这种方法做的，可参考。

**Comment by edgar-explorer** [comment]
谢谢，港科大这边Monocular Visual–Inertial State Estimation With Online Initialization and Camera–IMU
Extrinsic Calibration论文里面写的是重投影误差（几何误差）。我在想会不会有像DSO一样处理光度误差的，不知道哪个效果好。

**Comment by meyiao** [comment]
能考虑光度当然更好，但是不一定要在最后优化的时候加进去。可以在做特征点跟踪的时候就考虑光度，比如说一般我们都把特征点在图像上坐标的不确定度设成一个像素，但其实这个不确定度是应该根据光度来做调整的。

**Comment by meyiao** [comment]
ROVIO是用的光度误差。

**Comment by meyiao** [comment]
光流跟踪的特征点会慢慢飘移，能把光度处理好的话应该是会效果好些的。

**Comment by edgar-explorer** [comment]
好的，谢谢。还有就是您在那个视频最后说在光流跟踪的时候增加a和b来修正光度不变假设，是不是像Direct Visual-Inertial Odometry with Stereo Cameras这边论文说的那样。这边论文是在LSD-SLAM上加的IMU，联立方程里面相机误差好像是从光度误差计算出来，再算的投影误差。使用FAST特征点+LK光流，为最初是在SVO里面看到的，后面陆续又看了高博的代码ygz-stereo-inertial。感觉搞不明白了....

**Comment by meyiao** [comment]
只是在做光流跟踪的时候把光度变化考虑进去，我是参考的
Real-Time Feature Tracking and Outlier Rejection with Changes in Illumination
M. Hwangbo, J.-S. Kim, and T. Kanade, Inertial-aided KLT Feature Tracking for a Moving Camera

**Comment by cumtchenchang** [comment]
大哥，方便加下您的微信吗？我的18205205900。

**Comment by edgar-explorer** [comment]
这样啊，我最初以为是在计算误差的时候加上一种约束。看到Direct Visual-Inertial Odometry with Stereo Cameras这边论文里面公式4有着两个参数，以为是这样的。
