### ISSUE TITLE
關於compVq的問題

### ISSUE THREAD

**Issue by selinaliu0420** [meyiao/ImuFusion#3]
您好！
想要請問您compVq的公式是參考哪個reference?
而F矩陣如何求得?
因為沒有聯繫的方式，所以在github上留言請教您。謝謝。

**Comment by meyiao** [comment]
![image](https://user-images.githubusercontent.com/16507097/212636055-3b0a66d5-5bb1-4f79-95e4-1a7421cc7272.png)
